# Generated by Django 4.2.1 on 2023-05-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0002_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='성'),
        ),
    ]
