# Generated by Django 4.2.1 on 2023-05-11 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('description', models.CharField(max_length=100, verbose_name='설명')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('description', models.CharField(max_length=100, verbose_name='설명')),
                ('image', models.ImageField(upload_to='photo_studio/static/img/%Y/%m/%d', verbose_name='이미지')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_studio.album', verbose_name='앨범')),
            ],
        ),
    ]
