# Generated by Django 4.2.1 on 2023-05-11 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0004_album_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '앨범', 'verbose_name_plural': '앨범'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '사진', 'verbose_name_plural': '사진'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='album',
            name='last_date',
            field=models.DateField(auto_now=True, verbose_name='종료일'),
        ),
        migrations.AddField(
            model_name='album',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='시작일'),
            preserve_default=False,
        ),
    ]
