# Generated by Django 4.2.1 on 2023-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0005_alter_album_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='static/img/%Y/%m/%d', verbose_name='이미지'),
        ),
    ]
