# Generated by Django 4.2.1 on 2023-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='last_date',
            field=models.DateField(blank=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='album',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='시작일'),
        ),
    ]
