# Generated by Django 4.2.1 on 2023-05-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0007_alter_album_last_date_alter_album_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='last_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='album',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
    ]
