# Generated by Django 4.2.1 on 2023-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0008_alter_album_last_date_alter_album_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='property',
            field=models.CharField(default='', max_length=50, verbose_name='속성'),
        ),
    ]
