# Generated by Django 4.2.1 on 2023-05-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0009_photo_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ImageField(upload_to='static/img/templates', verbose_name='템플릿')),
                ('property', models.CharField(default='', max_length=50, verbose_name='속성')),
            ],
        ),
    ]
