# Generated by Django 4.2.1 on 2023-05-15 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0010_photo_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_templates',
            options={'verbose_name': '템플릿', 'verbose_name_plural': '템플릿'},
        ),
        migrations.RenameField(
            model_name='photo_templates',
            old_name='template',
            new_name='template_url',
        ),
    ]
