# Generated by Django 4.2.1 on 2023-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0011_alter_photo_templates_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='owner',
            field=models.CharField(default='', max_length=20, verbose_name='사용자'),
            preserve_default=False,
        ),
    ]
