# Generated by Django 4.2.1 on 2023-05-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0012_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='static/thumbnail/%Y/%m/%d', verbose_name='썸네일'),
        ),
    ]
