# Generated by Django 4.2.1 on 2023-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_studio', '0013_album_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='static/thumbnail', verbose_name='썸네일'),
        ),
    ]
